# Site settings
title: A Coding Journey
header-img: img/home-bg.png
email: annabelwilmerding@gmail.com
copyright_name: Awilmerding1
description: > # this means to ignore newlines until "baseurl:"
  My Experiences at Flatiron School
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Awilmerding1
learn_profile: Awilmerding1
email_username: annabelwilmerding@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
